name: Heroku Deployment
on:
  push:
    branches: [develop]
jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 14.x
        uses: actions/setup-node@v3
        with: 
          node-version: 14.x
      - name: Install dependencies
        run: yarn
      - name: Check lint
        run: yarn run lint
      - name: Run Test
        run: yarn run test
      - name: Deployment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_APP_EMAIL }}